version: "3.8"

services:
  db:
    image: "mysql:latest"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Welcome#123
    volumes:
      - "db:/var/lib/mysql"

  book-rest:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_NAME: mydb

volumes:
  db: